hmLoadTopic({
hmKeywords:"",
hmTitle:"US Cartridge, 105mm HE, M323 (T42)",
hmDescription:"Description HE Cartridge M323 is used for blast, fragmentation and mining.  This cartridge is composed of a steel projectile assembled with a pre engraved gilding metal rotat",
hmPrevLink:"cartridge_-105mm-he_-m38_-m38a.html",
hmNextLink:"cartridge_-105mm-he_-m413-(t33.html",
hmParentLink:"_usd.html",
hmBreadCrumbs:"<a href=\"_ord.html\">Ordnance<\/a> &gt; <a href=\"_projo.html\">Projectiles<\/a> &gt; <a href=\"_usd.html\">United States<\/a>",
hmTitlePath:"Ordnance > Projectiles > United States > Cartridge, 105mm HE, M323",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">US Cartridge, 105mm HE, M323 (T42)<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"text-align: center;\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"text-align: center;\"><div style=\"margin:0 auto 0 auto;width:100%;max-width:1121px;height:auto;\"><img alt=\"clip2290\" style=\"width:100%;height:auto;border:none\" src=\".\/images\/clip2290.png\"\/><\/div><\/div>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Description<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">HE Cartridge M323 is used for blast, fragmentation and mining. <\/span><\/p>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">This cartridge is composed of a steel projectile assembled with a pre engraved gilding metal rotating band and two indexing buttons. It contains a bursting charge of 4.38 pounds of <a href=\"tnt.html\" class=\"topiclink\">TNT<\/a>. This is a deep cavity projectile, containing a supplementary charge of .3 pound of TNT. The projectile may be assembled with either an impact or mechanical time impact fuze. The projectile is crimped to a perforated steel cartridge case. The propelling charge is packed in a rayon and\' plastic liner. A percussion primer is press fitted into the base of the cartridge case.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Hazardous Components<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">Main charge is 4.38 lbs of TNT. M32 cartridge case, M57 primer, M10 propelling charge (7.95 lb)<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">See Also<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">Nothing else to see.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Source(s)<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\"><a href=\"pdf\/TM-9-1300-203-1967.pdf#page=239\" target=\"_blank\" onclick=\"return HMTrackTopiclink(this);\" class=\"weblink\">TM 9-1300-203, Artillery Ammunition (1967)<\/a><\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
