hmLoadTopic({
hmKeywords:"",
hmTitle:"French Projectile, 155mm Smoke (WP), FIA",
hmDescription:"Description No description available. Functioning No information about functioning. Hazardous Components No information about hazardous components. See Also Nothing else",
hmPrevLink:"projectile_-155mm-smoke-(wp)_-.html",
hmNextLink:"projectile_-240mm-chemical_-m2.html",
hmParentLink:"_frd.html",
hmBreadCrumbs:"<a href=\"_ord.html\">Ordnance<\/a> &gt; <a href=\"_projo.html\">Projectiles<\/a> &gt; <a href=\"_frd.html\">France<\/a>",
hmTitlePath:"Ordnance > Projectiles > France > Projectile, 155mm Smoke (WP), FIA",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">French Projectile, 155mm Smoke (WP), FIA<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"text-align: center;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-align: center;\"><img alt=\"clip0655\" style=\"margin:0 auto 0 auto;width:32.8125rem;height:18.7500rem;border:none\" src=\".\/images\/clip0655.png\"\/><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Description<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">No description available.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Functioning<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">No information about functioning.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Hazardous Components<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">No information about hazardous components.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">See Also<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">Nothing else to see.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Source(s)<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\"><a href=\"pdf\/ID-Guide-Iraq.pdf#page=308\" target=\"_blank\" onclick=\"return HMTrackTopiclink(this);\" class=\"weblink\">Iraq Ordnance Identification Guide (2004)<\/a><\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
