hmLoadTopic({
hmKeywords:"",
hmTitle:"US Projectile, 105mm HERA, M548 (XM548E1)",
hmDescription:"Description No description available. Functioning No information about functioning. Hazardous Components No information about hazardous components. See Also MTSQ, M501",
hmPrevLink:"projectile_-105mm-heat_-m67.html",
hmNextLink:"projectile_-105mm-hera_-m912.html",
hmParentLink:"_usd.html",
hmBreadCrumbs:"<a href=\"_ord.html\">Ordnance<\/a> &gt; <a href=\"_projo.html\">Projectiles<\/a> &gt; <a href=\"_usd.html\">United States<\/a>",
hmTitlePath:"Ordnance > Projectiles > United States > Projectile, 105mm HERA, M548",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">US Projectile, 105mm HERA, M548 (XM548E1)<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"text-align: center;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-align: center;\"><img alt=\"clip0307\" style=\"margin:0 auto 0 auto;width:32.8125rem;height:18.7500rem;border:none\" src=\".\/images\/clip0307.png\"\/><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Description<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">No description available.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Functioning<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">No information about functioning.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Hazardous Components<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\">No information about hazardous components.<\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">See Also<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\"><a href=\"mtsq_-m501.html\" class=\"topiclink\">MTSQ, M501<\/a><\/span><\/p>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\"><a href=\"proximity_-m513.html\" class=\"topiclink\">Proximity, M513<\/a><\/span><\/p>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\"><a href=\"proximity_-m513a1.html\" class=\"topiclink\">Proximity, M513A1<\/a><\/span><\/p>\n\r<h2 class=\"p_Heading2\" style=\"page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading2\">Source(s)<\/span><\/h2>\n\r<p class=\"p_BodyTextIndented\"><span class=\"f_BodyTextIndented\"><a href=\"pdf\/ID-Guide-Iraq.pdf#page=230\" target=\"_blank\" onclick=\"return HMTrackTopiclink(this);\" class=\"weblink\">Iraq Ordnance Identification Guide (2004)<\/a><\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
